# Generated by Django 4.2.29 on 2026-04-16 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                (
                    "label",
                    models.CharField(
                        choices=[("cell", "Cell"), ("home", "Home"), ("work", "Work")],
                        default="cell",
                        max_length=10,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
