# Generated by Django 4.2.29 on 2026-04-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_1", models.CharField(max_length=255)),
                ("line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(default="Queens", max_length=100)),
                ("state", models.CharField(default="NY", max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
