API_ENDPOINT_SECTIONS = [
    {
        "title": "Authentication",
        "summary": "Token, session, and user bootstrap endpoints.",
        "endpoints": [
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/users/token/",
                "description": "Obtain JWT access and refresh tokens.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/users/csrf/",
                "description": "Issue a CSRF cookie for cookie-backed auth routes.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/users/token/refresh/",
                "description": "Refresh an access token.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/users/logout/",
                "description": "Clear the refresh cookie and end the current session.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/users/demo-login/",
                "description": "Log in with demo credentials when demo mode is enabled.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/users/register/",
                "description": "Register a new user.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/users/me/",
                "description": "Return the current user, organization membership, and facility context.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/users/me/preferences/",
                "description": "Update current-user preferences such as theme and last facility.",
            },
        ],
    },
    {
        "title": "Patient Portal",
        "summary": "Patient-scoped auth, self-service scheduling, profile, clinical summary, refills, and messaging.",
        "endpoints": [
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/auth/login/",
                "description": "Authenticate a patient portal account and issue a portal-scoped session.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/auth/refresh/",
                "description": "Refresh a portal-scoped access token.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/auth/logout/",
                "description": "Clear the portal refresh cookie and end the portal session.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/demo-login/",
                "description": "Log in with the synthetic patient demo account when demo mode is enabled.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/me/",
                "description": "Return the linked patient profile and portal preferences for the authenticated patient.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/portal/me/",
                "description": "Update patient-managed profile fields and portal preferences.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/portal/me/preferred-pharmacy/",
                "description": "Update the patient's preferred pharmacy within the effective facility pharmacy list.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/appointments/",
                "description": "List the patient's appointments.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/appointments/<id>/cancel/",
                "description": "Cancel an eligible portal appointment.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/scheduling/providers/",
                "description": "List providers available for portal self-scheduling.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/scheduling/appointment-types/",
                "description": "List appointment types exposed to portal self-scheduling.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/scheduling/slots/",
                "description": "List bookable portal scheduling slots.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/scheduling/book/",
                "description": "Book a portal appointment for the authenticated patient.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/medications/",
                "description": "List patient-visible active and historical medication records.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/refill-requests/",
                "description": "List the patient's refill requests.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/refill-requests/",
                "description": "Create a patient-initiated refill request for an active medication.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/refill-requests/<id>/cancel/",
                "description": "Cancel an eligible pending refill request.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/pharmacies/",
                "description": "List pharmacies available to the patient's facility.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/allergies/",
                "description": "List patient-visible allergy and adverse reaction records.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/medical-summary/",
                "description": "Return the patient's portal medical summary, including recent visits, vitals, medications, and allergies.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/messaging/threads/",
                "description": "List the patient's message threads.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/messaging/threads/",
                "description": "Start a patient message thread with the care team.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/portal/messaging/threads/<id>/",
                "description": "Retrieve one patient message thread.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/portal/messaging/threads/<id>/reply/",
                "description": "Reply to an open patient message thread.",
            },
        ],
    },
    {
        "title": "Organizations",
        "summary": "Organization profile and people administration.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/organizations/",
                "description": "Return the current organization for the authenticated user.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/organizations/<id>/",
                "description": "Retrieve organization overview details, members, and summary data.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/organizations/<id>/",
                "description": "Update organization contact and overview fields.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/organizations/people/",
                "description": "List organization people and roles.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/organizations/people/",
                "description": "Create a new organization-level user and membership.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/organizations/people/<id>/",
                "description": "Update organization person details and membership role.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/organizations/pharmacies/",
                "description": "List organization pharmacy preferences linked to the global directory.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/organizations/pharmacies/",
                "description": "Link an existing pharmacy or import a custom pharmacy for the organization.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/organizations/pharmacies/<id>/",
                "description": "Update organization pharmacy preference details.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/organizations/facility-pharmacy-overrides/?facility_id=<id>",
                "description": "List facility-specific pharmacy overrides.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/organizations/roles/",
                "description": "List organization role types.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/organizations/security/",
                "description": "List organization role security permissions.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/organizations/security/update-role/",
                "description": "Update organization role security permissions.",
            },
        ],
    },
    {
        "title": "Facilities",
        "summary": "Facility profile, staff, and configuration dictionaries.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/",
                "description": "List facilities for the current organization.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/facilities/<id>/",
                "description": "Update facility profile, operating hours, and operational details.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/staff/?facility_id=<id>",
                "description": "List facility staff assignments.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/appointment-statuses/?facility_id=<id>",
                "description": "List appointment statuses for a facility.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/appointment-types/?facility_id=<id>",
                "description": "List appointment types and scheduling defaults.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/resources/?facility_id=<id>",
                "description": "List rooms, providers, and schedule resources for a facility.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/staff-roles/?facility_id=<id>",
                "description": "List configurable staff roles.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/staff-titles/?facility_id=<id>",
                "description": "List staff titles.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/facilities/patient-genders/?facility_id=<id>",
                "description": "List patient gender options.",
            },
        ],
    },
    {
        "title": "Patients",
        "summary": "Patient records plus supporting clinical-contact data.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/patients/?facility_id=<id>&search=smith",
                "description": 'Quick patient lookup by last name or "Last, First".',
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/patients/?facility_id=<id>",
                "description": "Create a patient record in the selected facility.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/patients/<id>/?facility_id=<id>",
                "description": "Update patient demographics, care team, and pharmacy details.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/patients/<id>/reveal-ssn/?facility_id=<id>",
                "description": "Reveal a masked patient SSN and record an audit event.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/patients/document-categories/?facility_id=<id>",
                "description": "List patient document categories for a facility.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/patients/documents/?facility_id=<id>&patient_id=<id>",
                "description": "List document metadata for a patient.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/patients/documents/bundle/view/?facility_id=<id>",
                "description": "Build a combined preview PDF for selected patient documents.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/patients/pharmacies/?facility_id=<id>",
                "description": "List facility-effective pharmacies from organization pharmacy settings and facility overrides.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/patients/providers/?facility_id=<id>",
                "description": "List PCP and referring provider records for the selected facility.",
            },
        ],
    },
    {
        "title": "Insurance",
        "summary": "Insurance carrier dictionary and patient coverage records.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/insurance/carriers/?facility_id=<id>",
                "description": "List facility-effective insurance carriers from organization payer settings and facility overrides.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/insurance/organization-carriers/",
                "description": "List organization payer preferences.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/insurance/facility-carrier-overrides/?facility_id=<id>",
                "description": "List facility-specific payer overrides.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/insurance/policies/?facility_id=<id>&patient_id=<id>",
                "description": "List patient insurance policies within the selected facility.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/insurance/policies/?facility_id=<id>",
                "description": "Create a patient insurance policy.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/insurance/policies/<id>/?facility_id=<id>",
                "description": "Update patient insurance policy details.",
            },
        ],
    },
    {
        "title": "Appointments",
        "summary": "Scheduling, visit logistics, and appointment notes.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/appointments/?facility_id=<id>&date=2026-04-21",
                "description": "List appointments for a selected date.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/appointments/?facility_id=<id>",
                "description": "Create an appointment with visit mode, room, and instructions.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/appointments/<id>/?facility_id=<id>",
                "description": "Update appointment schedule, status, and operational notes.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/appointments/heatmap/?facility_id=<id>&month=2026-04",
                "description": "Return appointment counts per local date for a schedule heatmap.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/appointments/<id>/edit-session/?facility_id=<id>",
                "description": "Check appointment edit-session occupancy.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": (
                    "/v1/appointments/slot-hold/"
                    "?facility_id=<id>&start_time=<iso>&resource=<id>"
                ),
                "description": (
                    "Soft 'being booked' presence for an empty slot "
                    "(POST acquire/override, PATCH heartbeat, DELETE release)."
                ),
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/appointments/schedule-check/?facility_id=<id>",
                "description": "Check an interval for saved appointments and advisory booking presence; edits require a scoped appointment_id.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/appointments/booking-hold/?facility_id=<id>",
                "description": "Acquire or resize a booking session using JSON session_id, revision and interval; explicit take_over revokes overlapping sessions.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/appointments/booking-hold/?facility_id=<id>",
                "description": "Heartbeat an active owned session using JSON session_id and its current revision; cannot acquire or resize.",
            },
            {
                "method": "DELETE",
                "class": "delete",
                "path": "/v1/appointments/booking-hold/?facility_id=<id>&session_id=<uuid>&revision=<revision>",
                "description": "Release a booking session with a newer revision; retain a tombstone against delayed requests.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/appointments/<id>/history/?facility_id=<id>",
                "description": "List audit-style history for an appointment.",
            },
        ],
    },
    {
        "title": "Clinical",
        "summary": "Facility-scoped encounters, progress note charting, vitals, and diagnosis catalog.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/clinical/encounters/?facility_id=<id>&patient_id=<id>",
                "description": "List patient encounters and nested progress notes.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/clinical/encounters/?facility_id=<id>",
                "description": "Start a clinical encounter with an optional draft progress note.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/clinical/progress-notes/<id>/?facility_id=<id>",
                "description": "Update a draft progress note.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/clinical/progress-notes/<id>/sign/?facility_id=<id>",
                "description": "Sign a progress note and lock it from further edits.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/clinical/progress-notes/<id>/unsign/?facility_id=<id>",
                "description": "Reopen a signed progress note when the user is permitted.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/clinical/vitals/?facility_id=<id>&patient_id=<id>",
                "description": "List patient vital sign records for a facility.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/clinical/vitals/?facility_id=<id>",
                "description": "Record a new vital sign entry for a patient.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/clinical/vitals/<id>/?facility_id=<id>",
                "description": "Retrieve a single vital sign record.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/clinical/vitals/<id>/?facility_id=<id>",
                "description": "Update a vital sign record.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/clinical/icd10-catalog/",
                "description": "List ICD-10 diagnosis codes for clinical documentation.",
            },
        ],
    },
    {
        "title": "Medications",
        "summary": "Facility-scoped patient medication records, refill requests, prescriber delegations, and reference catalogs.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/medications/?facility_id=<id>&patient_id=<id>",
                "description": "List medication records for a patient.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/medications/?facility_id=<id>",
                "description": "Create a patient medication record.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/medications/<id>/?facility_id=<id>",
                "description": "Update medication details, status, dates, and notes.",
            },
            {
                "method": "DELETE",
                "class": "delete",
                "path": "/v1/medications/<id>/?facility_id=<id>",
                "description": "Mark a medication as discontinued.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/medications/refill-requests/?facility_id=<id>",
                "description": "List patient refill requests for a facility.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/medications/refill-requests/<id>/approve/?facility_id=<id>",
                "description": "Approve a pending refill request.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/medications/refill-requests/<id>/deny/?facility_id=<id>",
                "description": "Deny a pending refill request.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/medications/prescriber-delegations/?facility_id=<id>",
                "description": "List prescriber delegations for a facility.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/medications/prescriber-delegations/?facility_id=<id>",
                "description": "Create a prescriber delegation.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/medications/prescriber-delegations/<id>/?facility_id=<id>",
                "description": "Update a prescriber delegation.",
            },
            {
                "method": "DELETE",
                "class": "delete",
                "path": "/v1/medications/prescriber-delegations/<id>/?facility_id=<id>",
                "description": "Delete a prescriber delegation.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/medications/catalog/",
                "description": "List the medication reference catalog.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/medications/route-catalog/",
                "description": "List medication administration routes.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/medications/frequency-catalog/",
                "description": "List medication dosing frequency options.",
            },
        ],
    },
    {
        "title": "Allergies",
        "summary": "Facility-scoped patient allergy and adverse reaction records.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/allergies/patient-allergies/?facility_id=<id>&patient_id=<id>",
                "description": "List allergy and adverse reaction records for a patient.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/allergies/patient-allergies/?facility_id=<id>",
                "description": "Create a patient allergy or adverse reaction record.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/allergies/patient-allergies/<id>/?facility_id=<id>",
                "description": "Update allergy reaction, severity, status, onset, and notes.",
            },
            {
                "method": "DELETE",
                "class": "delete",
                "path": "/v1/allergies/patient-allergies/<id>/?facility_id=<id>",
                "description": "Mark an allergy record as entered in error.",
            },
        ],
    },
    {
        "title": "Messaging (Clinician)",
        "summary": "Clinician-side secure message threads. Thread creation is patient-initiated; clinicians list, read, reply, close, and reopen threads.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/messaging/threads/?facility_id=<id>",
                "description": "List secure message threads for the facility.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/messaging/threads/<id>/?facility_id=<id>",
                "description": "Retrieve a single message thread and its messages.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/messaging/threads/<id>/reply/?facility_id=<id>",
                "description": "Post a care-team reply to an open message thread.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/messaging/threads/<id>/close/?facility_id=<id>",
                "description": "Close an open message thread.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/messaging/threads/<id>/reopen/?facility_id=<id>",
                "description": "Reopen a closed message thread.",
            },
        ],
    },
    {
        "title": "Billing",
        "summary": "Encounter-linked superbills and charge capture.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/billing/encounter-billing-records/?facility_id=<id>&patient_id=<id>",
                "description": "List patient superbills and charge-capture records.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/billing/encounter-billing-records/?facility_id=<id>",
                "description": "Create a billing record for a signed encounter.",
            },
            {
                "method": "PATCH",
                "class": "patch",
                "path": "/v1/billing/encounter-billing-records/<id>/?facility_id=<id>",
                "description": "Update diagnosis codes, charge lines, and billing status.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/billing/fee-schedule-items/?facility_id=<id>",
                "description": "List facility-effective fee schedule items merged from organization defaults and facility overrides.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/billing/organization-fee-schedules/",
                "description": "List organization fee schedule sheets.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/billing/facility-fee-schedules/?facility_id=<id>",
                "description": "List facility-specific fee schedule sheets.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/billing/facility-fee-schedules/copy-from-org/?facility_id=<id>",
                "description": "Create a facility fee schedule from an organization schedule.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/billing/cpt-catalog/",
                "description": "List predefined CPT codes with descriptions and suggested fees.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/billing/organization-fee-schedules/<id>/populate/",
                "description": "Populate a fee schedule sheet with all predefined CPT codes that are not already present.",
            },
            {
                "method": "POST",
                "class": "post",
                "path": "/v1/billing/facility-fee-schedules/<id>/populate/?facility_id=<id>",
                "description": "Populate a facility fee schedule sheet with all predefined CPT codes that are not already present.",
            },
        ],
    },
    {
        "title": "Audit",
        "summary": "Read-only audit trail for organization admins and facility-scoped facility admins.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/audit/events/",
                "description": "List audit events. Organization admins can use scope=organization for org-only activity; facility admins must filter to a facility they manage. Filterable by action, app_label, facility, patient, and scope.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/v1/audit/events/<id>/",
                "description": "Retrieve a single audit event.",
            },
        ],
    },
    {
        "title": "System",
        "summary": "Health and operational entrypoints.",
        "endpoints": [
            {
                "method": "GET",
                "class": "get",
                "path": "/health/",
                "description": "Basic health check endpoint.",
            },
            {
                "method": "GET",
                "class": "get",
                "path": "/admin/",
                "description": "Django admin console.",
            },
        ],
    },
]
