# Generated by Codex on 2026-04-30

from datetime import timedelta

from django.db import migrations, models


def backfill_end_time(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")

    for appointment in Appointment.objects.select_related("appointment_type"):
        if not appointment.appointment_time or not appointment.appointment_type_id:
            continue
        appointment.end_time = appointment.appointment_time + timedelta(
            minutes=appointment.appointment_type.duration_minutes
        )
        appointment.save(update_fields=["end_time"])


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_remove_appointment_visit_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_end_time, migrations.RunPython.noop),
    ]
