# Generated by Django 4.2.29 on 2026-09-06 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0026_audit_documents_delete_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "appointments",
            "0016_appointmentslothold_uniq_slot_hold_facility_null_resource_start",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentBookingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(unique=True)),
                ("user_display_name", models.CharField(blank=True, max_length=150)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("released", "released"),
                            ("revoked", "revoked"),
                        ],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_holds",
                        to="facilities.facility",
                    ),
                ),
                (
                    "rendering_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_holds",
                        to="facilities.staff",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_holds",
                        to="facilities.facilityresource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_booking_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["facility", "resource", "start_time"],
                        name="booking_hold_resource_start",
                    ),
                    models.Index(
                        fields=["facility", "rendering_provider", "start_time"],
                        name="booking_hold_provider_start",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appointmentbookinghold",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("state", "active"), _negated=True),
                    models.Q(
                        ("end_time__isnull", False),
                        ("start_time__isnull", False),
                        ("end_time__gt", models.F("start_time")),
                    ),
                    _connector="OR",
                ),
                name="booking_hold_active_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentbookinghold",
            constraint=models.CheckConstraint(
                check=models.Q(("revision__gte", 1)),
                name="booking_hold_positive_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentbookinghold",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("state__in", ["active", "inactive", "released", "revoked"])
                ),
                name="booking_hold_valid_state",
            ),
        ),
    ]
